---
Name: yplay-overlay-config
After:
  - '#elemental'
  - '#deskall-page-blocks'
---
Page:
  extensions:
    - 'OverlayPageExtension'

PageController:
  extensions:
    - OverlayContentControllerExtension
  url_handlers:
    'element/$ID!': 'handleElement'