---
Name: yplay-overlay-config
After:
  - '#elemental'
  - '#deskall-page-blocks'
---
Page:
  extensions:
    - 'OverlayPageExtension'

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - OverlayContentControllerExtension
  url_handlers:
    'element/$ID!': 'handleElement'
    'bewertung-senden' : 'BewertungForm'