---
Name: deskall-divers
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-divers

SilverStripe\i18n\i18n:
  default_locale: 'de_DE'

Page:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
    - DeskallPageExtension
    - 'g4b0\SearchableDataObjects\SearchableDataObject'

PageController:
  extensions:
    - DeskallPageControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - deskall-divers/css/custom_admin.css
  extra_requirements_javascript:
    - deskall-divers/javascript/lang/de.js

SilverStripe\ORM\DataObject:
  extensions:
    - DeskallTranslatable
    - RestrictedOption

Sheadawson\Linkable\Models\Link:
  extensions:
    - LinkableLinkExtension

SilverStripe\Assets\FileNameFilter:
  extensions:
    - FileNameFilterExtension

---
Name: deskall-searchable-dataobjects-extensions
After: '#searchable-dataobjects-extensions'
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - CustomSearchExtension

g4b0\SearchableDataObjects\CustomSearch:
  exclude_from_search: 
    - SilverStripe\ErrorPage\ErrorPage