---
Name: deskall-blog
After:
    - '#deskall-divers'
    - '#deskall-page-blocks'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-blog

BaseBlockExtension:
  blocks:
    - SummaryBlogBlock

SilverStripe\Comments\Controllers\CommentingController:
  extensions:
    - 'DeskallCommentingControllerExtension'

Page:  
  comments:
    enabled: false

SilverStripe\Blog\Model\Blog:
  extensions:
    - BlogExtension

SilverStripe\Blog\Model\BlogPost:
  show_in_sitetree: true
  extensions:
    - BlogPostExtension
    - SilverStripe\Comments\Extensions\CommentsExtension
  comments:
    enabled: true

SilverStripe\Blog\Model\BlogCategory:
  extensions:
    - BlogCategoryExtension

SilverStripe\Blog\Model\BlogTag:
  extensions:
    - BlogTagExtension

SilverStripe\Comments\Extensions\CommentsExtension:
  comments:
    nested_comments: true
    nested_depth: 2
    require_moderation_cms: false
    require_moderation: true
    require_moderation_nonmembers: true
    frontend_moderation: false


