---
Name: cookroutes
After: framework/routes#coreroutes
---
Director:
  rules:
   'cook//$ID': 'Cook_Controller'
   'ad//$ID': 'EmployerAdvertisement_Controller'
   'order//$ID': 'PackageOrder_Controller'
   'account//$ID': 'Account_Controller'
   'application//$ID': 'Application_Controller'