---
Name: deskall-images
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-images

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - DeskallImageAssetFormFactoryExtension
  
SilverStripe\Assets\Image:
  MaxWidth: 2500
  MaxHeight: 2500
  memory: 512M
  extensions:
    - ImageExtension
SilverStripe\Filesystem\Storage\DBFile:
  extensions:
    - ImageExtension

SilverStripe\Assets\Storage\DBFile:
  force_resample: true

SilverStripe\Core\Injector\Injector:
 SilverStripe\Assets\Image_Backend:
   properties:
     Quality: 75
