---
Name: deskall-images
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-images

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - DeskallImageAssetFormFactoryExtension
  
SilverStripe\Assets\Image:
  MaxWidth: 2500
  MaxHeight: 2500
  memory: 256M
  extensions:
    - ImageExtension
SilverStripe\Filesystem\Storage\DBFile:
  extensions:
    - ImageExtension

SilverStripe\Assets\Storage\DBFile:
  force_resample: true

SilverStripe\Core\Injector\Injector:
 SilverStripe\Assets\Image_Backend:
   properties:
     Quality: 75

ImageExtension:
  sets:
    Slides:
      arguments:
        '(min-width: 1400px) and (min-device-pixel-ratio: 2.0)': [5000]
        '(min-width: 1400px)': [2500]
        '(min-width: 1200px) and (min-device-pixel-ratio: 2.0)': [2400]
        '(min-width: 1200px)': [1200]
        '(min-width: 1000px) and (min-device-pixel-ratio: 2.0)': [2000]
        '(min-width: 1000px)': [1000]
        '(min-width: 800px) and (min-device-pixel-ratio: 2.0)': [1600]
        '(min-width: 800px)': [800]
        '(min-width: 400px) and (min-device-pixel-ratio: 2.0)': [800]
        '(min-width: 400px)': [400]
      default_arguments: [2500]
      uikit: 'data-uk-cover'