---
Name: deskall-images
After:
    - '#focuspoint'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-images

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - DeskallImageAssetFormFactoryExtension
  
SilverStripe\Assets\Image:
  allowed_extensions:
    - svg
  MaxWidth: 2500
  MaxHeight: 2500
  optimise_tiny: false
  memory: 128M
  extensions:
    - ImageExtension

SilverStripe\Filesystem\Storage\DBFile:
  extensions:
    - ImageExtension
  force_resample: true

SilverStripe\Assets\File:
  force_resample: true
  allowed_extensions:
    - svg
  app_categories:
    image:
      - svg
    image/supported:
      - svg

SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
    properties:
      Quality: 90
  Intervention\Image\ImageManager:
    constructor:
      - { driver: imagick }

Kinglozzer\SilverStripeTinyPng\ImageExtension:
  tinypng_api_key: 'JJqVVtCMrcr0gDHcMDsZgD1F14KTztnC'

# ImageExtension:
#   successStatuses:
#     - 0
#   enabledCommands:
#     - jpegtran
#     - optipng
#   availableCommands:
#     jpg:
#       jpegtran: '%s -copy none -progressive -optimize -outfile %s %s'
#       jpegoptim: '%s -p --strip-all -m80 --all-progressive %s'
#     png:
#       optipng: '%s -o 2 -strip all %s'
#       pngquant: '%s --speed 10 --quality=80 ---ext=.png --force %s'
#     gif:
#       optipng: '%s -o 2 -strip all %s'
#   binDirectory: '/deskall-images/'
#   sets:
#     Slides:
#       method: FocusFill
#       arguments:
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 2000px),(min--moz-device-pixel-ratio: 2) and (min-width: 2000px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 2000px),(min-device-pixel-ratio: 2) and (min-width: 2000px),( min-resolution: 192dpi) and (min-width: 2000px),(min-resolution: 2dppx) and (min-width: 2000px)': [5000]
#         '(min-width: 2000px)': [2500]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1800px),(min--moz-device-pixel-ratio: 2) and (min-width: 1800px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1800px),(min-device-pixel-ratio: 2) and (min-width: 1800px),( min-resolution: 192dpi) and (min-width: 1800px),(min-resolution: 2dppx) and (min-width: 1800px)': [4000]
#         '(min-width: 1800px)': [2000]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1600px),(min--moz-device-pixel-ratio: 2) and (min-width: 1600px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1600px),(min-device-pixel-ratio: 2) and (min-width: 1600px),( min-resolution: 192dpi) and (min-width: 1600px),(min-resolution: 2dppx) and (min-width: 1600px)': [3600]
#         '(min-width: 1600px)': [1800]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1400px),(min--moz-device-pixel-ratio: 2) and (min-width: 1400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1400px),(min-device-pixel-ratio: 2) and (min-width: 1400px),( min-resolution: 192dpi) and (min-width: 1400px),(min-resolution: 2dppx) and (min-width: 1400px)': [3000]
#         '(min-width: 1400px)': [1600]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [2800]
#         '(min-width: 1200px)': [1400]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 400px),(min--moz-device-pixel-ratio: 2) and (min-width: 400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 400px),(min-device-pixel-ratio: 2) and (min-width: 400px),( min-resolution: 192dpi) and (min-width: 400px),(min-resolution: 2dppx) and (min-width: 400px)': [2400]
#         '(min-width: 10px)': [1200]
#       default_arguments: [1200]
#       uikit: 'data-uk-cover'
#     Banners:
#       method: FocusFill
#       arguments:
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1400px),(min--moz-device-pixel-ratio: 2) and (min-width: 1400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1400px),(min-device-pixel-ratio: 2) and (min-width: 1400px),( min-resolution: 192dpi) and (min-width: 1400px),(min-resolution: 2dppx) and (min-width: 1400px)': [5000,900]
#         '(min-width: 1400px)': [2500,450]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [2800,900]
#         '(min-width: 1200px)': [1400,450]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1000px),(min--moz-device-pixel-ratio: 2) and (min-width: 1000px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1000px),(min-device-pixel-ratio: 2) and (min-width: 1000px),( min-resolution: 192dpi) and (min-width: 1000px),(min-resolution: 2dppx) and (min-width: 1000px)': [2400,900]
#         '(min-width: 1000px)': [1200,450]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 800px),(min--moz-device-pixel-ratio: 2) and (min-width: 800px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 800px),(min-device-pixel-ratio: 2) and (min-width: 800px),( min-resolution: 192dpi) and (min-width: 800px),(min-resolution: 2dppx) and (min-width: 800px)': [2000,900]
#         '(min-width: 800px)': [1000,450]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 400px),(min--moz-device-pixel-ratio: 2) and (min-width: 400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 400px),(min-device-pixel-ratio: 2) and (min-width: 400px),( min-resolution: 192dpi) and (min-width: 400px),(min-resolution: 2dppx) and (min-width: 400px)': [1200,900]
#         '(min-width: 10px)': [600,450]
#       default_arguments: [600,450]
#       uikit: 'data-uk-cover'
#     Overlays:
#       method: FocusFill
#       arguments:
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1800px),(min--moz-device-pixel-ratio: 2) and (min-width: 1800px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1800px),(min-device-pixel-ratio: 2) and (min-width: 1800px),( min-resolution: 192dpi) and (min-width: 1800px),(min-resolution: 2dppx) and (min-width: 1800px)': [5000]
#         '(min-width: 1800px)': [2500]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1400px),(min--moz-device-pixel-ratio: 2) and (min-width: 1400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1400px),(min-device-pixel-ratio: 2) and (min-width: 1400px),( min-resolution: 192dpi) and (min-width: 1400px),(min-resolution: 2dppx) and (min-width: 1400px)': [4000]
#         '(min-width: 1400px)': [2000]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [3000]
#         '(min-width: 1200px)': [1500]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1000px),(min--moz-device-pixel-ratio: 2) and (min-width: 1000px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1000px),(min-device-pixel-ratio: 2) and (min-width: 1000px),( min-resolution: 192dpi) and (min-width: 1000px),(min-resolution: 2dppx) and (min-width: 1000px)': [2500]
#         '(min-width: 1000px)': [1250]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 800px),(min--moz-device-pixel-ratio: 2) and (min-width: 800px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 800px),(min-device-pixel-ratio: 2) and (min-width: 800px),( min-resolution: 192dpi) and (min-width: 800px),(min-resolution: 2dppx) and (min-width: 800px)': [2000]
#         '(min-width: 800px)': [1000]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 400px),(min--moz-device-pixel-ratio: 2) and (min-width: 400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 400px),(min-device-pixel-ratio: 2) and (min-width: 400px),( min-resolution: 192dpi) and (min-width: 400px),(min-resolution: 2dppx) and (min-width: 400px)': [1200]
#         '(min-width: 10px)': [600]
#       default_arguments: [600]
#       uikit: 'data-uk-cover'
#     Content:
#       arguments:
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 2000px),(min--moz-device-pixel-ratio: 2) and (min-width: 2000px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 2000px),(min-device-pixel-ratio: 2) and (min-width: 2000px),( min-resolution: 192dpi) and (min-width: 2000px),(min-resolution: 2dppx) and (min-width: 2000px)': [5000]
#         '(min-width: 2000px)': [2500]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1800px),(min--moz-device-pixel-ratio: 2) and (min-width: 1800px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1800px),(min-device-pixel-ratio: 2) and (min-width: 1800px),( min-resolution: 192dpi) and (min-width: 1800px),(min-resolution: 2dppx) and (min-width: 1800px)': [3600]
#         '(min-width: 1800px)': [1800]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1600px),(min--moz-device-pixel-ratio: 2) and (min-width: 1600px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1600px),(min-device-pixel-ratio: 2) and (min-width: 1600px),( min-resolution: 192dpi) and (min-width: 1600px),(min-resolution: 2dppx) and (min-width: 1600px)': [3200]
#         '(min-width: 1600px)': [1600]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1400px),(min--moz-device-pixel-ratio: 2) and (min-width: 1400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1400px),(min-device-pixel-ratio: 2) and (min-width: 1400px),( min-resolution: 192dpi) and (min-width: 1400px),(min-resolution: 2dppx) and (min-width: 1400px)': [2800]
#         '(min-width: 1400px)': [1400]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [2400]
#         '(min-width: 1200px)': [1200]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 1000px),(min--moz-device-pixel-ratio: 2) and (min-width: 1000px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1000px),(min-device-pixel-ratio: 2) and (min-width: 1000px),( min-resolution: 192dpi) and (min-width: 1000px),(min-resolution: 2dppx) and (min-width: 1000px)': [2000]
#         '(min-width: 1000px)': [1000]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 800px),(min--moz-device-pixel-ratio: 2) and (min-width: 800px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 800px),(min-device-pixel-ratio: 2) and (min-width: 800px),( min-resolution: 192dpi) and (min-width: 800px),(min-resolution: 2dppx) and (min-width: 800px)': [1600]
#         '(min-width: 800px)': [800]
#         #'(-webkit-min-device-pixel-ratio: 2) and (min-width: 400px),(min--moz-device-pixel-ratio: 2) and (min-width: 400px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 400px),(min-device-pixel-ratio: 2) and (min-width: 400px),( min-resolution: 192dpi) and (min-width: 400px),(min-resolution: 2dppx) and (min-width: 400px)': [800]
#         '(min-width: 10px)': [600]
#       default_arguments: [400]