---
Name: deskall-images
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-images

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - DeskallImageAssetFormFactoryExtension

SilverStripe\Assets\Image:
  allowed_extensions:
    - svg
  app_categories:
    image:
      - svg
    image_supported:
      -svg
  extensions:
   # - DeskallImageExtension

SilverStripe\Assets\File:
  force_resample: false
  allowed_extensions:
    - svg
  app_categories:
    image:
      - svg
    image_supported:
      -svg

SilverStripe\Filesystem\Storage\DBFile:
  extensions:
  #  - DeskallImageExtension

SilverStripe\Core\Injector\Injector:
 SilverStripe\Assets\Image_Backend:
   properties:
     Quality: 75
