---
Name: deskall-images
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-images

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - DeskallImageAssetFormFactoryExtension
  
SilverStripe\Assets\Image:
  MaxWidth: 2500
  MaxHeight: 2500
  extensions:
    - ImageExtension
SilverStripe\Filesystem\Storage\DBFile:
  extensions:
    - ImageExtension

SilverStripe\Assets\Storage\DBFile:
  force_resample: true

SilverStripe\Core\Injector\Injector:
 SilverStripe\Assets\Image_Backend:
   properties:
     Quality: 75

ImageExtension:
  sets:
    Slides:
      arguments:
        '(min-width: 1400px) and (min-device-pixel-ratio: 2.0)': [5000]
        '(min-width: 1400px)': [2500]
        '(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [2800]
        '(min-width: 1200px)': [1400]
        '(min-width: 1000px) and (min-device-pixel-ratio: 2.0)': [2400]
        '(min-width: 1000px)': [1200]
        '(min-width: 800px) and (min-device-pixel-ratio: 2.0)': [2000]
        '(min-width: 800px)': [1000]
        '(min-width: 400px) and (min-device-pixel-ratio: 2.0)': [1200]
        '(min-width: 400px)': [600]
      default_arguments: [2500]
      uikit: 'data-uk-cover'