---
Name: deskall-images
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-images

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - DeskallImageAssetFormFactoryExtension
  
SilverStripe\Assets\Image:
  allowed_extensions:
    - svg
  MaxWidth: 2500
  MaxHeight: 2500
  memory: 512M
  extensions:
    - ImageExtension
SilverStripe\Filesystem\Storage\DBFile:
  extensions:
    - ImageExtension

SilverStripe\Assets\Storage\DBFile:
  force_resample: true

SilverStripe\Assets\File:
  allowed_extensions:
    - svg
  app_categories:
    image:
      - svg
    image/supported:
      - svg


SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
    properties:
      Quality: 90
  Intervention\Image\ImageManager:
    constructor:
      - { driver: imagick }


ImageExtension:
  sets:
    Slides:
      method: FocusFill
      arguments:
        '(min-width: 1400px) and (min-device-pixel-ratio: 2.0)': [5000,2500]
        '(min-width: 1400px)': [2500,1250]
        '(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [2800,1400]
        '(min-width: 1200px)': [1400,700]
        '(min-width: 1000px) and (min-device-pixel-ratio: 2.0)': [2400,1200]
        '(min-width: 1000px)': [1200,600]
        '(min-width: 800px) and (min-device-pixel-ratio: 2.0)': [2000,100]
        '(min-width: 800px)': [1000,500]
        '(min-width: 400px) and (min-device-pixel-ratio: 2.0)': [1200,600]
        '(min-width: 10px)': [600,500]
      default_arguments: [600,500]
      uikit: 'data-uk-cover'
    Banners:
      method: FocusFill
      arguments:
        '(min-width: 1400px) and (min-device-pixel-ratio: 2.0)': [5000,900]
        '(min-width: 1400px)': [2500,450]
        '(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [2800,900]
        '(min-width: 1200px)': [1400,450]
        '(min-width: 1000px) and (min-device-pixel-ratio: 2.0)': [2400,900]
        '(min-width: 1000px)': [1200,450]
        '(min-width: 800px) and (min-device-pixel-ratio: 2.0)': [2000,900]
        '(min-width: 800px)': [1000,450]
        '(min-width: 400px) and (min-device-pixel-ratio: 2.0)': [1200,900]
        '(min-width: 10px)': [600,450]
      default_arguments: [600,450]
      uikit: 'data-uk-cover'
    Content:
      arguments:
        '(min-width: 1400px) and (min-device-pixel-ratio: 2.0)': [5000]
        '(min-width: 1400px)': [2500]
        '(-webkit-min-device-pixel-ratio: 2) and (min-width: 1200px),(min--moz-device-pixel-ratio: 2) and (min-width: 1200px),( -o-min-device-pixel-ratio: 2/1) and (min-width: 1200px),(min-device-pixel-ratio: 2) and (min-width: 1200px),( min-resolution: 192dpi) and (min-width: 1200px),(min-resolution: 2dppx) and (min-width: 1200px)': [2400]
        '(min-width: 1200px)': [1200]
        '(min-width: 1000px) and (min-device-pixel-ratio: 2.0)': [2000]
        '(min-width: 1000px)': [1000]
        '(min-width: 800px) and (min-device-pixel-ratio: 2.0)': [1600]
        '(min-width: 800px)': [800]
        '(min-width: 400px) and (min-device-pixel-ratio: 2.0)': [800]
        '(min-width: 10px)': [400]
      default_arguments: [400]