---
Name: deskall-seo
After:
    - '#deskall-divers'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-seo

SilverStripe\CMS\Models\SiteTree:
  extensions:
    - Deskall\SEO\SEOPageExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Deskall\SEO\SEOSiteConfigExtension
    
# Example of how to exclude extra page types from showing the SEO tab:
Deskall\SEO\SeoObjectExtension:
  excluded_page_types:
    - 'ErrorPage'
    - 'VirtualPage'

# Example of how to set content fields to be used for a page type
#NewPage:
#  SeoContent:
#    - 'ContentField1'
#    - 'ContentField2'