---
Name: deskall-theme
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-theme


SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - FooterExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - deskall-themes/css/SiteConfigLayout.css