---
Name: bak-products
After:
    - '#deskall-divers'
    - '#deskall-page-blocks'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: bak-products

BaseBlockExtension:
  blocks:
    - Bak-Products-Blocks-ProductBlock

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - BAK\Products\BAKSiteConfigExtension

BAK\Products\Models\Product:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

BAK\Products\Models\ProductCategory:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

BAK\Products\Models\ProductUsage:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

BAK\Products\Models\ProductUseArea:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

TractorCow\Fluent\Extension\FluentDirectorExtension:
  disable_default_prefix: true