---
Name: bak-products
After:
    - '#deskall-divers'
    - '#deskall-page-blocks'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: bak-products

BaseBlockExtension:
  blocks:
    - Bak-Products-Blocks-ProductBlock
    - Bak-Products-Blocks-ProductCategoryBlock

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - BAK\Products\BAKSiteConfigExtension

BAK\Products\Models\Product:
  extensions:
    - 'DeskallFluentExtension'

BAK\Products\Models\ProductCategory:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

BAK\Products\Models\ProductUsage:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

BAK\Products\Models\ProductUseArea:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'

SliderBlock:
  extensions:
    - 'BAK\Products\BAKSliderBlockExtension'

Sheadawson\Linkable\Models\Link:
  extensions:
    - 'BAK\Products\BAKProductLinkExtension'

Sheadawson\Linkable\Forms\LinkField:
  extensions:
    - Bak\Products\LinkableProduct