---
Name: bak-products
After:
    - '#deskall-divers'
    - '#deskall-page-blocks'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: bak-products

BaseBlockExtension:
  blocks:
    - Bak-Products-Blocks-ProductBlock