---
Name: bak-news
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: bak-news

BAK\News\NewsPage:
  extensions:
    - Terraformers\EmbargoExpiry\Extension\EmbargoExpiryExtension

BaseBlockExtension:
  blocks:
    - Bak-News-Blocks-BAKLastNewsBlock