---
Name: bak-news
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: bak-news

SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Bak\News\Forms\GridFieldPublishItemRequestExtension

BAK\News\Models\News:
  extensions:
    - 'TractorCow\Fluent\Extension\FluentExtension'