---
Name: deskall-page-blocks
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-page-blocks

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - BaseBlockExtension
    - Activable
    - Linkable

DNADesign\Elemental\ElementalEditor:
  extensions:
    - ElementalEditorExtension

Page:
  extensions:
    - PageBlocksExtension

Slide:
  extensions:
    - Activable
    - Linkable

SilverStripe\UserForms\Form\UserForm:
  extensions:
    - UserDefinedFormExtension


DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - UserFormExtension