---
Name: deskall-page-blocks
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-page-blocks

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - BaseBlockExtension
    - Activable
    - Linkable

DNADesign\Elemental\ElementalEditor:
  extensions:
    - ElementalEditorExtension

Page:
  extensions:
    - PageBlocksExtension

Slide:
  extensions:
    - Activable
    - Linkable

SilverStripe\UserForms\Form\UserForm:
  extensions:
   - UserDefinedFormExtension


DNADesign\ElementalUserForms\Model\ElementForm:
  email_template_directory: /themes/primaklima/templates/emails/
  extensions:
    - UserFormExtension

SilverStripe\UserForms\Model\Recipient\EmailRecipient:
  allow_unbound_recipient_fields: true

SilverStripe\UserForms\Control\UserDefinedFormController:
  extensions:
    - UserDefinedFormControllerExtension