---
Name: deskall-page-blocks
After:
    - '#deskall-divers'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-page-blocks

DNADesign\Elemental\Controllers\ElementController:
  include_default_styles: false

DNADesign\Elemental\Models\BaseElement:
  default_global_elements: true
  extensions:
    - BaseBlockExtension
    - Activable
    - Linkable
    - Collapsable
    - 'g4b0\SearchableDataObjects\SearchableDataObject'
    - 'VirtualBlockExtension'

ParentBlock:
  extensions:
    - 'VirtualBlockExtension'


DNADesign\Elemental\ElementalEditor:
  extensions:
    - DeskallElementalEditorExtension

Page:
  extensions:
    - PageBlocksExtension

Slide:
  extensions:
    - Activable
    - Linkable
    - SubObjectPermission

Box:
  extensions:
    - SubObjectPermission

ListItem:
  extensions:
    - SubObjectPermission

Features:
  extensions:
    - SubObjectPermission

VideoObject:
  extensions:
    - SubObjectPermission

SilverStripe\UserForms\Form\UserForm:
  extensions:
   - UserDefinedFormExtension
  block_default_userforms_js: true
  block_default_userforms_css: true

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - deskall-page-blocks/css/block_editor.css

FormBlock:
  email_template_directory: deskall-page-blocks/templates/emails/

SilverStripe\UserForms\Model\Recipient\EmailRecipient:
  allow_unbound_recipient_fields: true

SilverStripe\UserForms\UserForm:
  cascade_duplicates:
    - 'EmailRecipients'

SilverStripe\UserForms\Control\UserDefinedFormController:
  extensions:
    - UserDefinedFormControllerExtension

SilverStripe\Forms\FormField:
  extensions:
  - 'DeskallFormFieldExtension'

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - DeskallContentControllerExtension
  url_handlers:
    'children/$ID!/$OTHERID!': 'handleChildren'


DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - FormBlockExtension
    - 'g4b0\SearchableDataObjects\SearchableDataObject'

SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
    default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector
