---
Name: deskall-page-blocks
After:
    - '#deskall-divers'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-page-blocks

DNADesign\Elemental\Controllers\ElementController:
  include_default_styles: false

DNADesign\Elemental\Models\BaseElement:
  default_global_elements: true
  extensions:
    - BaseBlockExtension
    - Activable
    - Linkable
    - Collapsable
    - PublishableBlock
    - BlockPublishingEngine

DNADesign\Elemental\ElementalEditor:
  extensions:
    - DeskallElementalEditorExtension

Page:
  extensions:
    - PageBlocksExtension

Slide:
  extensions:
    - Activable
    - Linkable
    - SubObjectPermission
    - PublishableBlock
    - BlockPublishingEngine

Box:
  extensions:
    - SubObjectPermission
    - PublishableBlock
    - BlockPublishingEngine

ListItem:
  extensions:
    - SubObjectPermission
    - PublishableBlock
    - BlockPublishingEngine

SilverStripe\UserForms\Form\UserForm:
  extensions:
   - UserDefinedFormExtension


SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - deskall-page-blocks/css/block_editor.css

DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - UserFormExtension

SilverStripe\UserForms\Model\Recipient\EmailRecipient:
  allow_unbound_recipient_fields: true

SilverStripe\UserForms\Control\UserDefinedFormController:
  extensions:
    - UserDefinedFormControllerExtension

SilverStripe\Forms\FormField:
  extensions:
    - 'DeskallFormFieldExtension'