---
Name: deskall-page-blocks
After:
  - '#userformsconfig'
  - '#elemental'
  - '#linkable'
  - '#deskall-divers'
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-page-blocks

DNADesign\Elemental\Controllers\ElementController:
  include_default_styles: false

DNADesign\Elemental\Models\BaseElement:
  default_global_elements: true
  extensions:
    - BaseBlockExtension
    - Activable
    - Linkable
    - Collapsable
    - 'g4b0\SearchableDataObjects\SearchableDataObject'
    - 'VirtualBlockExtension'

ParentBlock:
  extensions:
    - 'VirtualBlockExtension'


DNADesign\Elemental\ElementalEditor:
  extensions:
    - DeskallElementalEditorExtension

Page:
  extensions:
    - PageBlocksExtension

Slide:
  extensions:
    - Activable
    - Linkable
    - SubObjectPermission

Box:
  extensions:
    - SubObjectPermission

ListItem:
  extensions:
    - SubObjectPermission

Features:
  extensions:
    - SubObjectPermission

VideoObject:
  extensions:
    - SubObjectPermission

SilverStripe\UserForms\Control\UserDefinedFormController:
  finished_anchor: ''
  extensions:
    - UserDefinedFormControllerExtension

SilverStripe\UserForms\Form\UserForm:
  extensions:
   - UserDefinedFormExtension

SilverStripe\UserForms\Model\UserDefinedForm:
  upgrade_on_build: false

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - deskall-page-blocks/css/block_editor.css

SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - DeskallContentControllerExtension
  url_handlers:
    'children/$ID!/$OTHERID!': 'handleChildren'

SilverStripe\UserForms\Model\Recipient\EmailRecipient:
  allow_unbound_recipient_fields: true
  extensions:
    - SubObjectPermission

DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - 'ElementFormExtension'
    - 'g4b0\SearchableDataObjects\SearchableDataObject'
  block_default_userforms_js: true
  block_default_userforms_css: true
  # cascade_duplicates:
  #   - 'EmailRecipients'
  #   - 'Fields'

SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
    default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector

Sheadawson\Linkable\Models\Link:
  extensions:
    - BlockLinkExtension
