---
Name: deskall-page-blocks
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: deskall-page-blocks

DNADesign\Elemental\Models\BaseElement:
  default_global_elements: true
  extensions:
    - BaseBlockExtension
    - Activable
    - Linkable
    - Collapsable
    - PublishParent

DNADesign\Elemental\ElementalEditor:
  extensions:
    - DeskallElementalEditorExtension

Page:
  extensions:
    - PageBlocksExtension

Slide:
  extensions:
    - Activable
    - Linkable
    - SubObjectPermission

Box:
  extensions:
    - SubObjectPermission

SilverStripe\UserForms\Form\UserForm:
  extensions:
   - UserDefinedFormExtension


SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - deskall-page-blocks/css/block_editor.css

DNADesign\ElementalUserForms\Model\ElementForm:
  email_template_directory: mysite/templates/email/
  extensions:
    - UserFormExtension

SilverStripe\UserForms\Model\Recipient\EmailRecipient:
  allow_unbound_recipient_fields: true

SilverStripe\UserForms\Control\UserDefinedFormController:
  extensions:
    - UserDefinedFormControllerExtension

SilverStripe\Forms\FormField:
  extensions:
    - 'DeskallFormFieldExtension'